version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /workflows/workflow.wdl
    readMePath: /README.md
    testParameterFiles:
      - test/Dockstore.json
    authors:
      - name: Anand Maurya
        email: anand.maurya@well.oc.ac.uk